name: Deployment Pipeline

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test_backend:
    name: Run Tests (Unit)
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm --filter @feature-flag/backend prisma generate

      - name: Run Unit Tests
        run: pnpm --filter @feature-flag/backend test

  build_backend:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: test_backend
    environment: test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest

  build_frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest

  deploy_backend:
    name: Deploy Backend & Seed
    runs-on: ubuntu-latest
    needs: build_backend
    environment: test
    steps:
      - name: Deploy to Dokku
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.YMS_HOST }}
          username: root
          key: ${{ secrets.YMS_SSH_KEY }}
          script: |
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest
            dokku ps:rebuild toggle-api
            yes | docker image prune --filter="label=app=toggle-api"

      - name: Run Migrations & Seed
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.YMS_HOST }}
          username: root
          key: ${{ secrets.YMS_SSH_KEY }}
          script: |
            dokku run toggle-api npm run start:seed

  deploy_frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: build_frontend
    environment: test
    steps:
      - name: Deploy to Dokku
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.YMS_HOST }}
          username: root
          key: ${{ secrets.YMS_SSH_KEY }}
          script: |
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest
            dokku ps:rebuild toggle-frontend
            yes | docker image prune --filter="label=app=toggle-frontend"
